name: Test github actions
 
on:
  schedule:
    - cron: '20 24 * * *'  #utc时间，北京时间小8个小时，实际24:20+8=32:20
 
jobs: # 执行的工作
  run_demo_actions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8.13"]

    steps:
       - uses: actions/checkout@v3
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v3
         with:
           python-version: ${{ matrix.python-version }}
           
       - name: Install requirements.txt
         run: | # 安装依赖包
          pip install -r requirements.txt 
 
       - name: 小桔签到
         run: python xiaoju/xiaoju.py

       - name: 龙湖天街签到、抽奖
         run: python lhtj/run.py
